// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CwWuCVkTStvpPlAzyKnQ6IfmObSs5Ow',
    appId: '1:812873289648:web:ac90d89dd1c44569c2d075',
    messagingSenderId: '812873289648',
    projectId: 'login-project-24d07',
    authDomain: 'login-project-24d07.firebaseapp.com',
    storageBucket: 'login-project-24d07.firebasestorage.app',
    measurementId: 'G-PZG2BNMHM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhPF7L1eT-u8zFXU61xv2hYTanK-W_Ek',
    appId: '1:812873289648:android:fedfb0c7916ef589c2d075',
    messagingSenderId: '812873289648',
    projectId: 'login-project-24d07',
    storageBucket: 'login-project-24d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNqSecqmzApx9-ssk7nhgZG8I8qw23rvw',
    appId: '1:812873289648:ios:f12a23a2065a8d3ac2d075',
    messagingSenderId: '812873289648',
    projectId: 'login-project-24d07',
    storageBucket: 'login-project-24d07.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNqSecqmzApx9-ssk7nhgZG8I8qw23rvw',
    appId: '1:812873289648:ios:f12a23a2065a8d3ac2d075',
    messagingSenderId: '812873289648',
    projectId: 'login-project-24d07',
    storageBucket: 'login-project-24d07.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-CwWuCVkTStvpPlAzyKnQ6IfmObSs5Ow',
    appId: '1:812873289648:web:61e8d4fc2930d620c2d075',
    messagingSenderId: '812873289648',
    projectId: 'login-project-24d07',
    authDomain: 'login-project-24d07.firebaseapp.com',
    storageBucket: 'login-project-24d07.firebasestorage.app',
    measurementId: 'G-CKE6365YZ4',
  );

}